config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions:'users/sessions' }

  devise_scope :user do
    get "/user/confirmation" => "users/registrations#confirmation"
    get "/user/success" => "users/registrations#success"
  end

  root "welcome#index"

  get "/preparedness" => "welcome#preparedness"
  get "/terms" => "welcome#terms"
  get "/help" => "welcome#help"
  get "/about_alerts" => "welcome#about_alerts"

  get "disaster_events/earthquakes" => "disaster_events#earthquakes"
  get "disaster_events/fires" => "disaster_events#fires"
  get "disaster_events/rivers" => "disaster_events#rivers"
  get "disaster_events/tsunami" => "disaster_events#tsunami"
  get "disaster_events/weather" => "disaster_events#weather"

  namespace :admin do
    get "/fires" => "event_maps#fires"
    get "/earthquakes" => "event_maps#earthquakes"
    get "/rivers" => "event_maps#rivers"
    get "/weather" => "event_maps#weather"
    get "/tsunami" => "event_maps#tsunami"

    resources :campaigns, except: [:edit, :update] do
      get :archived, on: :collection

      resources :alerts, only: [:new, :create]
    end
  end

  resources :alerts, only: [:index]

  resources :apidocs, only: [:index]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user && current_user.admin
      redirect_to admin_campaigns_path
    elsif current_user
      redirect_to edit_user_registration_path
    end
  end

  def preparedness
    if params[:id]
      alert = Alert.find(params[:id])

      alert.update(opened_total: (alert.opened_total += 1))
    end
  end

  def terms
  end

  def help
  end

  def about_alerts
  end
end

app/views/welcome/about_alerts.erb
<div class="signup-page__container">


  <div class="signup-page__terms-title">
    About Alerts
  </div>

  <div class="signup-page__term-details">
    <p>
      There are 4 different levels of alerts including non-emergency, advisory, voluntary evacuation, and mandatory evacuations.
    </p>

    <p>
      Notifications can be about weather, fire, floods, tsunamis, and brushfires.
    </p>

    <p>
      In the body of the SMS message, it will be clear what the notification is about (fire, flood) and how urgent it is (non-emergency or evacuation). There will always be a link to get more details. <b>It is important to click this link for every alert message you receive, including non-emergencies</b>. The California alert team uses your response to determine their next steps. If people aren't getting the notifications they may have to send out emergency teams to check on people and spread the word - especially in the case of evacuations.
    </p>

    <a href="/">
      <button id="signup-page__next-button" class="signup-page__next-button usa-button-primary">
        OK
      </button>
    </a>

  </div>

</div>

app/views/welcome/help.erb
<main class="user">

  <div class="user__title">
    Send us an email to get help or info
  </div>

  <div class="user__detail">
    We want to help you in anyway we can. Your questions or comments will be emailed to us, and you will receive a reply
    as soon as we are able.
  </div>

  <div class="user__box-area">
    <div class="user__label">
      <%= label_tag :subject, "Subject", class: "user__label-title" %>
      <div class="user__label-required">Required</div>
    </div>
    <%= text_field_tag :subject, "", autofocus: true, class: "user__input" %>
  </div>

  <div class="user__box-area">
    <div class="user__label">
      <%= label_tag :question, "Questions/Comments", class: "user__label-title" %>
      <div class="user__label-required">Required</div>
    </div>
    <%= text_area_tag :question, "", autofocus: true, class: "user__input" %>
  </div>

  <a href="/">
    <button id="signup-page__next-button" class="signup-page__next-button usa-button-primary">
      Send
    </button>
  </a>

</main>

app/views/welcome/index.erb
<div class="welcome">
  <div class="welcome__main-image">
  </div>

  <div class="welcome__container">
    <div class="welcome__message">
      <div class="welcome__message-image"></div>
      <div class="welcome__message-safe">We want you to stay safe!</div>
      <div class="welcome__message-alert">Sign up to receive alerts from your state and local government about your safety and community!</div>
      <div class="welcome__message-context">California Connects enables you to receive notifications regarding community hazards.  For example:  If a fire is on your street or an earthquake is about to happen, CaliConnects will send you location based alerts.  If you get an alert, the system has intelligently determined that you need the details to stay safe, because you are within the affected area. This also means you won't receive alerts that don't affect you.</div>
      <br>
      <%= link_to "Learn about the alerts", about_alerts_path, class: "welcome__about", target: "_blank"  %>

    </div>

    <div class="welcome__buttons">
      <%= button_to "Sign Up", new_user_registration_path, method: :get, class: "usa-button-primary" %>    
    </div>

    <div class="welcome__buttons">
      <%= button_to "Login", new_user_session_path, method: :get, class: "usa-button-primary" %>
    </div>

  </div>
</div>

app/views/welcome/preparedness.erb
<main  class="user">
  <h1 class="user__title">
    Be Prepared
  </h1>

  <div class="user__detail">This information will help you be prepared in case of an emergency.</div>

  <ul>
    <li>Here’s a link to California Storms <a href="http://storms.ca.gov/">website</a> to gain more information and resources.
    </li>
    <li>Here’s a link to the: <a href="https://www.ready.gov/kit">Basic Disaster Supplies Kit</a>.</li>
    <li>Here’s a link to
      <a href="http://www.conservation.ca.gov/cgs/information/Pages/EdResCenter.aspx">educational resources</a> on California’s
      Department of Conservation.
    </li>
    <li>Here’s a link to <a href="https://www2.usgs.gov/faq/?q=taxonomy/term/9762">USGS Data and Resources</a>.</li>
  </ul>
</main>

app/views/welcome/terms.erb
<div class="signup-page__container">


  <div class="signup-page__terms-title">
    Sample Terms and Conditions
  </div>

  <div class="signup-page__term-details">
      <p>
        IBM plans to protect your privacy and adhere to CalOPPA. This app, however, is a prototype and will not be used for
        commercial use.
      </p>

      <p>
        IBM uses information we collect to operate, maintain and provide you the features and functionality of Service, to
        analyze how the Service is used, diagnose service or technical problems, maintain security, personalize context,
        send you alerts via mobile and web, and track users as necessary to comply with the Digital Millennium Copyright Act
        and other applicable laws.
      </p>

      <p>IBM adheres to CalOPPA by being transparent:</p>

      <ul>
        <li>
          You provide us information, such as: your name, email, phone number, and your location and address. If you
          register for an account with California Connects Alert System, all information you choose to provide on the
          Service will be the viewable and discoverable by other admin users and open source technology parties, in
          accordance with your subscription to the California Connects Alert System.
        </li>

        <li>
          If you would like to cancel your subscription to the service, you can cancel your profile in the ‘Manage Profile’
          tab.
        </li>

        <li>
          Our privacy policy is effective March 1st, 2017. If our policy changes, we will give you 90 days’ notice of
          change, if you plan to continue to subscribe
        </li>

        <li>
          Only for this prototype, IBM will not track its subscribers over time and across third party websites to provide
          targeted advertising and therefore does not respond to Do Not Track (DNT) signals. However, some third party sites
          do keep track of your browsing activities when they serve you content, which enables them to tailor what they
          present to you. If you are visiting such sites, Safari allows you to set the DNT signal on your browser so that
          third parties (particularly advertisers) know you do not want to be tracked.
        </li>

        <li>
          Due to the nature of this prototype, we will not share your information beyond open source technology partners,
          who are integrated into our service and must also adhere to the CalOPPA. The open source technologies used are
          monitored for security on a regular basis.
        </li>
      </ul>



  </div>

</div>