config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions:'users/sessions' }

  devise_scope :user do
    get "/user/confirmation" => "users/registrations#confirmation"
    get "/user/success" => "users/registrations#success"
  end

  root "welcome#index"

  get "/preparedness" => "welcome#preparedness"
  get "/terms" => "welcome#terms"
  get "/help" => "welcome#help"
  get "/about_alerts" => "welcome#about_alerts"

  get "disaster_events/earthquakes" => "disaster_events#earthquakes"
  get "disaster_events/fires" => "disaster_events#fires"
  get "disaster_events/rivers" => "disaster_events#rivers"
  get "disaster_events/tsunami" => "disaster_events#tsunami"
  get "disaster_events/weather" => "disaster_events#weather"

  namespace :admin do
    get "/fires" => "event_maps#fires"
    get "/earthquakes" => "event_maps#earthquakes"
    get "/rivers" => "event_maps#rivers"
    get "/weather" => "event_maps#weather"
    get "/tsunami" => "event_maps#tsunami"

    resources :campaigns, except: [:edit, :update] do
      get :archived, on: :collection

      resources :alerts, only: [:new, :create]
    end
  end

  resources :alerts, only: [:index]

  resources :apidocs, only: [:index]
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :alerts, dependent: :destroy

  def formatted_date
    Time.at(date).in_time_zone("Pacific Time (US & Canada)").strftime("%A, %d %b %Y %H:%M %p")
  end

  def self.categories
    [:earthquake, :fire, :river_gauge, :tsunami, :weather, :other]
  end
end

app/controllers/admin/campaign_controller.rb
class Admin::CampaignController < ApplicationController
  def index
    @campaigns = Campaign.all.order(:updated_at)
  end

  def create
    Campaign.create(date: Time.now.to_i)

    redirect_to :admin_campaign_index
  end
end

app/controllers/admin/campaigns_controller.rb
class Admin::CampaignsController < ApplicationController
  before_action :verify_is_admin

  def index
    @campaigns = Campaign.where(archived: false).order(updated_at: :desc).limit(20)
  end

  def archived
    @campaigns = Campaign.where(archived: true).order(updated_at: :desc).limit(20)
  end

  def new
    @campaign = Campaign.new
    @campaign.alerts.build
  end

  def create
    campaign = Campaign.new(
      campaign_params.merge(date: Time.now.to_i)
    )

    if campaign.save
      alert = Alert.new(alert_params.merge({ campaign_id: campaign.id }))

      redirect_to admin_campaigns_path, notice: "Campaign Created"

      if alert.save
        alert.send_notifications(params, preparedness_url)
      end
    end
  end

  def show
    @campaign = Campaign.find_by(id: params[:id])

    redirect_to admin_campaigns_path, alert: "Campaign Not Found" unless @campaign
  end

  def destroy
    @campaign = Campaign.find(params[:id]).update(archived: true)

    redirect_to admin_campaigns_path, notice: "Campaign Archived"
  end

  private

  def campaign_params
    params.require(:campaign).permit(:name)
  end

  def alert_params
    alert_params = params.dig(:campaign, :alerts)

    if alert_params
      alert_params.permit(:severity, :description)
    else
      {}
    end
  end
end

app/views/admin/campaigns/archived.erb
<div class="admin__container">

  <%= render partial: 'admin/shared/admin_sidebar' %>

  <main class="admin__active">
    <section class="archived-campaigns" id="archived-campaigns">
      <div class="archived-campaigns__title">Archived Campaigns</div>
      <table class="archived-campaigns__table">
        <thead >
        <tr>
          <th class="archived-campaigns__table-header"></th>
          <th class="archived-campaigns__table-header">Category</th>
          <th class="archived-campaigns__table-header">Campaign Name</th>
          <th class="archived-campaigns__table-header">Recipients</th>
          <th class="archived-campaigns__table-header"># of notifications sent in Campaign</th>
          <th class="archived-campaigns__table-header">Time Stamp</th>
          <th class="archived-campaigns__table-header">Show</th>
        </tr>
        </thead>
        <tbody>
        <% @campaigns.each do |campaign| %>
            <% alerts = campaign.alerts %>
            <tr>
              <td class="active-campaigns__table-item-color"></td>
              <td class="active-campaigns__table-item">
                <%= to_human_readable(alerts.last.severity) unless alerts.empty? %>
              </td>
              <td class="active-campaigns__table-item">
                <%= campaign.name.capitalize %>
              </td>
              <td class="active-campaigns__table-item">
                <%= to_human_readable(alerts.last.received_total) unless alerts.empty? %>
              </td>
              <td class="active-campaigns__table-item">
                <%= to_human_readable(alerts.count) unless alerts.empty? %>
              </td>
              <td class="archived-campaigns__table-item">
                <%= campaign.formatted_date %>
              </td>
              <td class="archived-campaigns__table-item">
                <%= link_to "show", admin_campaign_path(campaign.id), method: :get %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

    </section>

  </main>

</div>

app/views/admin/campaigns/index.erb
<div class="admin__container">

  <%= render partial: 'admin/shared/admin_sidebar' %>

  <main class="admin__active">

    <section class="active-campaigns" id="active-campaigns">

      <div class="active-campaigns__title">Active Campaigns</div>

      <%= button_to "Create New Campaign", new_admin_campaign_path, method: :get, class: "usa-button-primary" %>

      <table class="active-campaigns__table">
        <thead >
          <tr>
            <th class="active-campaigns__table-header"></th>
            <th class="active-campaigns__table-header">Category</th>
            <th class="active-campaigns__table-header">Campaign Name</th>
            <th class="active-campaigns__table-header">Recipients</th>
            <th class="active-campaigns__table-header"># of notifications sent in Campaign</th>
            <th class="active-campaigns__table-header">Time Stamp</th>
            <th class="active-campaigns__table-header">Create</th>
            <th class="active-campaigns__table-header">View</th>
            <th class="active-campaigns__table-header">Delete</th>
          </tr>
        </thead>
        <tbody>
            <% @campaigns.each do |campaign| %>
                <% alerts = campaign.alerts %>
                <tr>
                  <td class="active-campaigns__table-item-color"></td>
                  <td class="active-campaigns__table-item">
                    <%= to_human_readable(alerts.last.severity) unless alerts.empty? %>
                  </td>
                  <td class="active-campaigns__table-item">
                    <%= campaign.name.capitalize %>
                  </td>
                  <td class="active-campaigns__table-item">
                    <%= to_human_readable(alerts.last.received_total) unless alerts.empty? %>
                  </td>
                  <td class="active-campaigns__table-item">
                    <%= to_human_readable(alerts.count) unless alerts.empty? %>
                  </td>
                  <td class="active-campaigns__table-item">
                    <%= campaign.formatted_date %>
                  </td>
                  <td class="active-campaigns__table-item">
                    <%= link_to "create alert", new_admin_campaign_alert_path(campaign.id), method: :get %>
                  </td>
                  <td class="active-campaigns__table-item">
                    <%= link_to "view", admin_campaign_path(campaign.id), method: :get %>
                  </td>
                  <td class="active-campaigns__table-item">
                    <%= link_to "end campaign", admin_campaign_path(campaign.id), method: :delete %>
                  </td>
                </tr>
              <% end %>
        </tbody>
      </table>
  </section>

</main>

</div>

app/views/admin/campaigns/new.erb
<div class="admin__container">

  <%= render partial: 'admin/shared/admin_sidebar' %>

  <main class="admin__new-campaign">

    <section class="new-campaign">

      <%= form_for [:admin, @campaign] do |f| %>
          <div class="new-campaign__title">New Campaign</div>
          <h5 class="new-campaign__minor-title">Title</h5>
          <p class="new-campaign__title-message">
            You are starting a new campaign. You must name the campaign first. A campaign is used to group together all notifications relating to a specific event.
          </p>

          <%= f.label :name, "Title", class: "new-campaign__label-title" %>
          <%= f.text_field :name, class: "new-campaign__label-field" %>

          <%= f.fields_for :alerts do |alerts_form| %>
              <%= render partial: 'admin/shared/alert_form', :locals => {:form => alerts_form} %>
          <% end %>

          <%= f.submit "Send Notification" %>
      <% end %>

    </section>

  </main>

</div>

app/views/admin/campaigns/show.erb
<div class="admin__container">

  <%= render partial: 'admin/shared/admin_sidebar' %>

  <main class="admin__show-campaign">

    <section class="show-campaign">

      <div class="show-campaign__header">
        <div>
          <div class="show-campaign__header-title-label">Campaign name</div>
          <div class="show-campaign__header-title"><%= @campaign.name %></div>
        </div>
        <%= button_to "End campaign", admin_campaign_path(@campaign), method: :delete, class: "show-campaign__header-button" %>
      </div>

      <%= button_to "Create Notification", new_admin_campaign_alert_path(@campaign), method: :get %>

      <ul class="show-campaign__alert-list">
        <div id="accordion">

          <% @campaign.alerts.each do |alert| %>
              <h1><%= alert.created_at.in_time_zone("Pacific Time (US & Canada)") %></h1>

              <div>
                <li>
                  <div class="show-campaign__alert-title">SMS Message:</div>
                  <p class="show-campaign__alert-detail"><%= alert.description + ", " + to_human_readable(alert.severity) %></p>

                  <div class="show-campaign__alert-title">Location Designation:</div>

                  <div class="show-campaign__alert-title">Recipient Analytics:</div>
                  <p class="show-campaign__alert-detail"><%= "Total Recipients: " + alert.received_total.to_s %></p>

                  <p class="show-campaign__alert-detail"><%= "Confirmed: " + alert.opened_total.to_s %></p>

                  <p class="show-campaign__alert-detail"><%= "Not Confirmed: " + (alert.received_total - alert.opened_total).to_s %></p>

                </li>
              </div>
          <% end %>
        </div>
      </ul>

    </section>

  </main>

</div>