config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions:'users/sessions' }

  devise_scope :user do
    get "/user/confirmation" => "users/registrations#confirmation"
    get "/user/success" => "users/registrations#success"
  end

  root "welcome#index"

  get "/preparedness" => "welcome#preparedness"
  get "/terms" => "welcome#terms"
  get "/help" => "welcome#help"
  get "/about_alerts" => "welcome#about_alerts"

  get "disaster_events/earthquakes" => "disaster_events#earthquakes"
  get "disaster_events/fires" => "disaster_events#fires"
  get "disaster_events/rivers" => "disaster_events#rivers"
  get "disaster_events/tsunami" => "disaster_events#tsunami"
  get "disaster_events/weather" => "disaster_events#weather"

  namespace :admin do
    get "/fires" => "event_maps#fires"
    get "/earthquakes" => "event_maps#earthquakes"
    get "/rivers" => "event_maps#rivers"
    get "/weather" => "event_maps#weather"
    get "/tsunami" => "event_maps#tsunami"

    resources :campaigns, except: [:edit, :update] do
      get :archived, on: :collection

      resources :alerts, only: [:new, :create]
    end
  end

  resources :alerts, only: [:index]

  resources :apidocs, only: [:index]
end

app/views/admin/shared/_admin_sidebar.erb
<a class="skip-link" href="#main">Skip to main content</a>

<nav class="sidebar">
  <div class="sidebar__notification-title">Notification Campaigns</div>
  <ul class="sidebar__notification-list">
    <li class="sidebar__notification-item"><%= link_to "Active Campaigns", admin_campaigns_path %></li>
    <li class="sidebar__notification-item"><%= link_to "New Campaigns", new_admin_campaign_path %></li>
    <li class="sidebar__notification-item"><%= link_to "Archived Campaigns", archived_admin_campaigns_path %></li>
  </ul>
  <div class="sidebar__event-title">Event Maps and Data</div>
  <ul class="sidebar__event-list">
    <li class="sidebar__event-item"><%= link_to "Fire", admin_fires_path %></li>
    <li class="sidebar__event-item"><%= link_to "Earthquake", admin_earthquakes_path %></li>
    <li class="sidebar__event-item"><%= link_to "River Gauge", admin_rivers_path %></li>
    <li class="sidebar__event-item"><%= link_to "Weather Hazards", admin_weather_path %></li>
    <li class="sidebar__event-item"><%= link_to "Tsunami", admin_tsunami_path %></li>
  </ul>
</nav>

app/views/admin/shared/_alert_form.erb
<div class="alert-form">

  <fieldset>
    <div class="alert-form__notification-title">Notification Type</div>
    <p class="alert-form__notification-message">
      Select a notification categorization
    </p>

    <% Alert.severities.each do |severity| %>
        <ul class="alert-form__notification-list">
          <li>
            <%= form.label :severity, to_human_readable(severity), class: "alert-form__label" %>
            <%= form.radio_button :severity, severity%>
          </li>
        </ul>
    <% end %>
  </fieldset>

  <div class="alert-form__notification-title">
      <%= form.label :description, "Notification Message" %>
  </div>

  <p class="alert-form__notification-message">
    This will be your first message.
  </p>

  <div class="alert-form__notification-textarea">
    <div class="alert-form__notification-textarea-header">
      <div>Message Text</div>
      <div>Characters: <span id="character-count">0</span></div>
    </div>
    <%= form.text_area :description, row: "15", class: "alert-form__notification-textarea-input"%>
  </div>


  <div class="alert-form__notification-title">Location Designation</div>
  <p class="alert-form__notification-message">
    Setting a location at the street, city, or zip level will include all recipients registered in that area to recieve the notification
  </p>

  <button class="admin-alert-location-button usa-button-outline" data-locationlevel="3">Street Level</button>
  <button class="admin-alert-location-button usa-button-outline" data-locationlevel="2">Zip Level</button>
  <button class="admin-alert-location-button usa-button-outline" data-locationlevel="1">City Level</button>

  <div id="location-container-1" class="location-container">
    <%= label_tag :city, nil, class: "alert-form__label" %>
    <%= text_field_tag :city %>
  </div>

  <div id="location-container-2" class="location-container">
    <%= label_tag :zipcode, nil, class: "alert-form__label" %>
    <%= text_field_tag :zipcode %>
  </div>

  <div id="location-container-3" class="location-container">
    <%= label_tag :street, nil, class: "alert-form__label" %>
    <%= text_field_tag :street %>

    <%= label_tag :street_city, nil, class: "alert-form__label"  %>
    <%= text_field_tag :street_city %>
  </div>

  <div id="admin-alert-marker"></div>

</div>