config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions:'users/sessions' }

  devise_scope :user do
    get "/user/confirmation" => "users/registrations#confirmation"
    get "/user/success" => "users/registrations#success"
  end

  root "welcome#index"

  get "/preparedness" => "welcome#preparedness"
  get "/terms" => "welcome#terms"
  get "/help" => "welcome#help"
  get "/about_alerts" => "welcome#about_alerts"

  get "disaster_events/earthquakes" => "disaster_events#earthquakes"
  get "disaster_events/fires" => "disaster_events#fires"
  get "disaster_events/rivers" => "disaster_events#rivers"
  get "disaster_events/tsunami" => "disaster_events#tsunami"
  get "disaster_events/weather" => "disaster_events#weather"

  namespace :admin do
    get "/fires" => "event_maps#fires"
    get "/earthquakes" => "event_maps#earthquakes"
    get "/rivers" => "event_maps#rivers"
    get "/weather" => "event_maps#weather"
    get "/tsunami" => "event_maps#tsunami"

    resources :campaigns, except: [:edit, :update] do
      get :archived, on: :collection

      resources :alerts, only: [:new, :create]
    end
  end

  resources :alerts, only: [:index]

  resources :apidocs, only: [:index]
end

app/controllers/admin/event_maps_controller.rb
class Admin::EventMapsController < ApplicationController
  def fires
  end

  def earthquakes
  end

  def rivers
  end

  def weather
  end

  def tsunami
  end
end

app/views/admin/event_maps/earthquakes.erb
<div class="admin__container">

  <%= render partial: 'admin/shared/admin_sidebar' %>

  <main class="admin__data-maps">

    <section class="data-maps">
      <div class="data-maps__title">Earthquakes</div>

      <div class="data-maps__images">
        <div class="data-maps__images-map">
          <div class="data-maps__image-title">Current</div>
          <div class="data-maps__image" id="earthquakes"></div>
        </div>

      </div>

      <div id="earthquake-data"></div>
      <table id="earthquake-data--table" class="usa-table-borderless">
        <tr class="data-maps__table-data">
          <th scope="col">Description</th>
          <th scope="col">Timestamp</th>
          <th scope="col">Link</th>
        </tr>
      </table>

      <div id="earthquake-url" style="display: none"><%= disaster_events_earthquakes_url %></div>

    </section>
  </main>
</div>

app/views/admin/event_maps/fires.erb
<div class="admin__container">

  <%= render partial: 'admin/shared/admin_sidebar' %>

  <main class="admin__data-maps">

    <section class="data-maps">
      <div class="data-maps__title">Fire</div>

      <div class="data-maps__images">
        <div class="data-maps__images-map">
          <div class="data-maps__image-title">Current</div>
          <div class="data-maps__image" id="fires"></div>
        </div>

      </div>

      <div id="fire-data"></div>
      <table id="fire-data--table" class="usa-table-borderless">
        <tr class="data-maps__table-data">
          <th scope="col">Description</th>
          <th scope="col">Timestamp</th>
          <th scope="col">Link</th>
        </tr>
      </table>

      <div id="fire-url" style="display: none"><%= disaster_events_fires_url %></div>

    </section>
  </main>
</div>

app/views/admin/event_maps/rivers.erb
<div class="admin__container">

  <%= render partial: 'admin/shared/admin_sidebar' %>

  <main class="admin__data-maps">

    <section class="data-maps">
      <div class="data-maps__title">River Gauge</div>

      <div class="data-maps__images">
        <div class="data-maps__images-map">
          <div class="data-maps__image-title">Current</div>
          <div class="data-maps__image" id="rivers"></div>
        </div>

      </div>

      <div id="rivers-data"></div>
      <table id="rivers-data--table" class="usa-table-borderless">
        <tr class="data-maps__table-data">
          <th scope="col">Description</th>
          <th scope="col">Timestamp</th>
          <th scope="col">Link</th>
        </tr>
      </table>

      <div id="rivers-url" style="display: none"><%= disaster_events_rivers_url %></div>

    </section>
  </main>
</div>

app/views/admin/event_maps/tsunami.erb
<div class="admin__container">

  <%= render partial: 'admin/shared/admin_sidebar' %>

  <main class="admin__data-maps">

    <section class="data-maps">
      <div class="data-maps__title">Tsunami</div>

      <div class="data-maps__images">
        <div class="data-maps__images-map">
          <div class="data-maps__image-title">Current</div>
          <div class="data-maps__image" id="tsunami"></div>
        </div>

      </div>

      <div id="tsunami-data"></div>
      <table id="tsunami-data--table" class="usa-table-borderless">
        <tr class="data-maps__table-data">
          <th scope="col">Description</th>
          <th scope="col">Timestamp</th>
          <th scope="col">Link</th>
        </tr>
      </table>

      <div id="tsunami-url" style="display: none"><%= disaster_events_tsunami_url %></div>

    </section>
  </main>
</div>

app/views/admin/event_maps/weather.erb
<div class="admin__container">

  <%= render partial: 'admin/shared/admin_sidebar' %>

  <main class="admin__data-maps">

    <section class="data-maps">
      <div class="data-maps__title">Weather Hazards</div>

      <div class="data-maps__images">
        <div class="data-maps__images-map">
          <div class="data-maps__image-title">Current</div>
          <div class="data-maps__image" id="hazards"></div>
        </div>

      </div>

      <div id="weather-data"></div>
      <table id="weather-data--table" class="usa-table-borderless">
        <tr class="data-maps__table-data">
          <th scope="col">Description</th>
          <th scope="col">Timestamp</th>
          <th scope="col">Link</th>
        </tr>
      </table>

      <div id="weather-url" style="display: none"><%= disaster_events_weather_url %></div>

    </section>
  </main>
</div>